spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_ai2
    username: root
    password: star2lim@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-time: 1h
    refresh-token-validity-time: 14d

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
